version: "3"

services:
  api:
    build: ./api
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=staging
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
    links:
      - neo4j
    depends_on:
      - neo4j
  ui:
    build:
      context: ./ui
      args:
        - SAPPER_APP_GRAPHQL_URI=http://localhost:4001/graphql
        - NODE_ENV=staging
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=staging
      - SSR_GRAPHQL_URI=http://api:4001/graphql
    links:
      - api
    depends_on:
      - api
